import { writeFileSync } from "node:fs";
import { catalogosRegistrados } from "../src/i18n";

export function isPublicMessage(key: string): boolean {
  return !/^(?:panel\.|adminError\.|adminForm\.|setup\.|preflight\.|wa\.)/.test(
    key
  );
}
const catalogs = Object.fromEntries(
  Object.entries(catalogosRegistrados()).map(([lang, messages]) => [
    lang,
    Object.fromEntries(
      Object.entries(messages).filter(([key]) => isPublicMessage(key))
    ),
  ])
);
writeFileSync(
  "src/i18n/public-catalogs.ts",
  `// Generated by pnpm i18n:client. Edit the full catalogs, then regenerate.\nexport const publicCatalogs: Record<string, Record<string, string>> = ${JSON.stringify(catalogs, null, 2)};\n`
);
